SELECT PATIENT_ID, SERVICE_DATE 
       FROM RX_FILL_INFO
       WHERE SERVICE_DATE BETWEEN SYSDATE -7 AND SYSDATE
       ORDER BY SERVICE_DATE;
       
SELECT PATIENT_ID, SERVICE_DATE, 
       SERVICE_DATE - BIRTH_DATE AS NBR_DAYS_BETWEEN
       FROM RX_FILL_INFO
       WHERE SERVICE_DATE BETWEEN SYSDATE - 7 AND SYSDATE
       ORDER BY SERVICE_DATE;