SELECT INTERVAL '5-0' YEAR TO MONTH AS INT1
    FROM DUAL;

SELECT INTERVAL '5' YEAR AS INT1 FROM DUAL;

SELECT INTERVAL '60' MONTH AS INT1 FROM DUAL;

SELECT INTERVAL '325-3' YEAR(3) TO MONTH AS INT FROM DUAL;