SELECT INTERVAL '5' DAY AS INT1 FROM DUAL;

SELECT INTERVAL '12' HOUR AS INT1 FROM DUAL;

SELECT INTERVAL '29' MINUTE AS INT1 FROM DUAL;

SELECT INTERVAL '47' SECOND AS INT1 FROM DUAL;

SELECT INTERVAL '23.5' SECOND AS INT1 FROM DUAL;

SELECT INTERVAL '47:23.5' MINUTE TO SECOND AS INT1 FROM DUAL;

